name: CI/CD Pipeline

on:
  pull_request:
    types: [closed]
    branches:
      - staging  # Trigger on merges to the staging branch
      - main      # Trigger on merges to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t learn-actions:${{ github.sha }} .  # Tag with the commit SHA
        env:
          DOCKER_BUILDKIT: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job completes successfully

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        if: github.event.pull_request.base.ref == 'staging' && github.event.pull_request.merged == true
        run: |
          docker tag learn-actions:${{ github.sha }} learn-actions:staging  # Tag the image for staging
          docker push learn-actions:staging

      - name: Push Docker image to Production
        if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.merged == true
        run: |
          docker tag learn-actions:${{ github.sha }} learn-actions:latest  # Tag the image for production
          docker push learn-actions:latest
